### ISSUE TITLE
When the kernel implementation will be released?

### ISSUE THREAD

**Issue by helloyongyang** [ilur98/DGQ#1]
Thank you for your work and open-source projects. May I ask when the kernel implementation will be released?

**Comment by ilur98** [comment]
Thank you for your attention! Sorry for the delay in the release plan.  Last month, I spent quite a time on my other paper revision. And I recently had pneumonia and influenza A. I will try my best to focus on the reconstructing the kernel implementation in these two weeks. I will notify you after I release the code of kernels.

**Comment by casper-hansen** [comment]
Also looking forward to the next release! Will it include W8A8 kernels?

**Comment by ilur98** [comment]
> Thank you for your work and open-source projects. May I ask when the kernel implementation will be released?

Our kernels have been released. You can have a try.

**Comment by ilur98** [comment]
> Also looking forward to the next release! Will it include W8A8 kernels?

You can remove the launch_dequant function to obtain a W8A8 Gemm kernels.
